export const JOB_STATES = {
    CREATED: "CREATED",
    COMPILING: "COMPILING",
    RUNNING: "RUNNING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    TIMEOUT: "TIMEOUT",
    KILLED: "KILLED",
    CLEAN: "CLEAN"
}